### ISSUE TITLE
能否改成随机签到时间

### ISSUE THREAD

**Issue by husv** [peng4740/Tieba_Github-Actions#1]
感谢大佬的这个项目，刚刚试了签到成功了。
另外提个建议，能否改成随机签到时间？我知道可以自己改签到时间，但我相信绝大数人都是拿来就用的，以后如果用的人多了，所有人一窝蜂在同一时间签到，会不会被百度检测到然后采取一些封锁措施？比如把Github Actions的服务器IP给屏蔽了，那就凉凉了。。。如果大佬改成随机时间，这样所有人无需修改，直接就是不同的签到时间。

**Comment by simon-sudo** [comment]
自己改改定时任务就行了，我觉得随机的不好实现（总不能每次签到后让读写配置文件然后提交吧？，很污染commit的）

**Comment by peng4740** [comment]
可以，晚上再加。

**Comment by husv** [comment]
大佬威武，测试正常，随机延时后签到成功。没问题的话隔壁天翼云也安排上吧。

**Comment by husv** [comment]
大佬，关于天翼的安全问题，看下我发给你164*******@qq.com邮箱的邮件
