### ISSUE TITLE
请问多账号怎样添加

### ISSUE THREAD

**Issue by Dingzhenpiyi** [peng4740/Tieba_Github-Actions#2]
感谢大佬的项目！！！请问多账号怎样添加？

**Comment by peng4740** [comment]
暂不支持，以后加

**Comment by Dingzhenpiyi** [comment]
> 暂不支持，以后加
好的，谢谢！

**Comment by peng4740** [comment]
更新了，你可以把代码合并过去或者重新Fork试一下。我没有多个贴吧账号，没有具体测试。

**Comment by Dingzhenpiyi** [comment]
> 更新了，你可以把代码合并过去或者重新Fork试一下。我没有多个贴吧账号，没有具体测试。

收到，大佬辛苦！
