### ISSUE TITLE
cron时间问题

### ISSUE THREAD

**Issue by misaka-h** [peng4740/Tieba_Github-Actions#7]
workflow中的cron表达式会在0:15和12:15开始任务，而不是“12:15-13:00之间和20:15-21:00之间各签到一次”

**Comment by 8888668** [comment]
签到开始前会执行random time然后开始运行😅

**Comment by misaka-h** [comment]
> 签到开始前会执行random time然后开始运行

呃，我的意思是workflow的时间设置：
![cron](https://img.imgdb.cn/item/5ffa47e03ffa7d37b32108e0.png)
其表示的actions触发时间和readme中的不符。（ **当然有可能是我理解错了** ）

**Comment by peng4740** [comment]
代码中的时区是UTC0，描述中转为我们习惯东8区就是这样子。
