### ISSUE TITLE
建议作者整点正事吧，实在不行找个电子厂上上班，滥用action还写中文，我都觉得丢脸

### ISSUE THREAD

**Issue by VergLsm** [peng4740/Tieba_Github-Actions#9]

**Comment by peng4740** [comment]
这仓库建立的时候(2020年5月)不违反当时的条款，详见官方docs仓库，那里能看到条款的更新记录。
怕你找不到，我直接给你找好了。补充的滥用条款是2021年5月份更新的。
https://github.com/github/docs/commit/c1ce4bf998708444e53d4154885570a9add01be5#diff-214ed496c870282367dc1b20e849b56ce55f0405abe814c20f4feee00d6bc135

不知道你为什么这么快得到这个新的消息，又找到我这个老的仓库。
